# Generated by Django 4.1.3 on 2022-11-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Koan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("koan", models.TextField(max_length=16777215)),
                (
                    "status",
                    models.IntegerField(choices=[(1, "Active"), (0, "Inactive")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField()),
            ],
        ),
    ]
