# Generated by Django 4.1.3 on 2022-11-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("koans", "0004_remove_koan_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="koan",
            name="updated_at",
        ),
    ]
